### ISSUE TITLE
Feedback on Edited Profile

### ISSUE THREAD

**Issue by watrall** [matrix-msu/Kora3#79] opened 2018-05-02 00:03 UTC
adding feedback in UI about a successful profile edit would be very helpful ("Profile Edited" or some such).  Sometimes hard to tell immediately if the profile has been edited because user is pushed back into the same editing page (as opposed to being pushed back to the View Profile page)

**Comment by austintruchan** [comment] 2018-05-02 00:55
This might be a duplicate of https://github.com/matrix-msu/Kora3/issues/49 Which is all about the implementation of notifications (still to be developed). I looked and saw that Profile Updated is listed as an instance to create a success notification.

**Comment by fritosxii** [comment] 2018-05-02 13:17
This will also be improved with form validation reporting as well

**Closed** 2018-05-02 15:48 UTC
Labels: duplicate
