### ISSUE TITLE
Geolocator Map - Show all Default Locations at once on load.

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#398] opened 2018-11-29 21:12 UTC
Right now, the geolocator map on the single record, or record card shows only one point on load, even if the geolocator has multiple locations. It would be ideal if the map was zoomed out enough on load to show all points at once.

**Comment by Dev34** [comment] 2019-01-25 19:21
Geolocator maps on records page (record cards) and single record page are now zoomed to contain all the markers on the map.

This is on the geolocator-zoom-#398 branch (pushed to GitHub)

**Comment by austintruchan** [comment] 2019-01-28 16:17
Do you have a record you could point me to that has this?

**Comment by Dev34** [comment] 2019-01-28 17:45
Records Page (record card):
![geolocatorzoomrecordcard](https://user-images.githubusercontent.com/12753141/51855026-3f427880-22fa-11e9-8aba-69cb4155c8b3.PNG)

Single record page:
![geolocatorzoomsinglerecordpage](https://user-images.githubusercontent.com/12753141/51855031-41a4d280-22fa-11e9-9290-f3498532aa44.PNG)

In case you wanted a link: [http://robbie-72.matrix.msu.edu/~rainier.devolder/Kora3/public/projects/48/forms/90/records](url)
Use username ```testuser``` and pw ```test123```

**Comment by austintruchan** [comment] 2019-02-04 21:02
Ok these look good. 

I noticed the border radiuses are no longer there for the maps though. Are they gone for you too? If so please fix.

**Comment by Dev34** [comment] 2019-02-06 19:12
The current border-radius for the maps is only 5px, which is why it looks like it isn't there. I have increased it to 10px.
If you want to play around with it, you can enter something like ```$('.geolocator-map').css('border-radius', '15px');``` into the browser console.

Please run ```compass compile```
This is on the geolocator-zoom-#398 branch (pushed to GitHub)

**Comment by austintruchan** [comment] 2019-02-11 15:17
The border radiuses should be 5px, what I am saying is that the border radiuses are 0px and are a sharp point.

Here is what I see: 
<img width="824" alt="screen shot 2019-02-11 at 10 16 37 am" src="https://user-images.githubusercontent.com/5408529/52572632-3b2c5580-2de6-11e9-97b2-2074756b2c8e.png">

**Comment by Dev34** [comment] 2019-02-11 19:46
Okay, I've found the issue and added a hack so that the maps can be rounded in Safari and I also changed border-radius back to 5px.

Please run ```compass compile```
This is on the geolocator-zoom-#398 branch (pushed to GitHub)

**Comment by austintruchan** [comment] 2019-02-14 19:10
Border radiuses are back!

One thing I noticed is that selecting the full screen option for the map seems to not work. Can you see if this is because of the additions you made to the map, or if its just something else?

**Comment by Dev34** [comment] 2019-02-22 20:33
I can confirm that the full-screen option not working was due to my border-radius fix for Safari. I have found a way to unapply and apply my previous fix when entering/exiting full-screen, so full-screen should be working again.
One problem that I'm sure you'll notice right away is that the map is not zoomed to contain all the markers in full-screen. I added code to fix this that _should_ work, but it seems that this is a known-bug with Leaflet so I won't be able to fix that (https://github.com/Leaflet/Leaflet.fullscreen/issues/78)).

Please run `compass compile`
This is on the geolocator-zoom-#398 branch (pushed to GitHub)

**Comment by austintruchan** [comment] 2019-03-05 15:43
This looks good.

Last thing I noticed is that map fields seem to be above the fixed navigation bar. Make sure the navigation bar remains above the maps when scrolling. 
<img width="958" alt="screen shot 2019-03-05 at 10 39 50 am" src="https://user-images.githubusercontent.com/5408529/53817405-5bf25180-3f33-11e9-8749-24640ddb8272.png">


That and update the box shadow of the close button, to be the same as the full screen / open in new tab buttons that are on the non full screen map. 
<img width="69" alt="screen shot 2019-03-05 at 10 41 35 am" src="https://user-images.githubusercontent.com/5408529/53817412-5eed4200-3f33-11e9-914e-2ab494f81722.png">

**Comment by Dev34** [comment] 2019-04-17 20:13
Pushed a fix for the navigation bar being underneath the geolocator maps when scrolling. Tried to find the cause of the broken full-screen modal.
Finally got to test this issue on a Safari device.

**Comment by Dev34** [comment] 2019-04-19 17:23
Added a CSS change that fixes the maps appearing above the navigation bar. Disabled the full-screen button (for now). The 'open in a new tab' button now redirects to a page where the map is also zoomed to contain all of the markers.

**Comment by austintruchan** [comment] 2019-04-19 17:53
Looks good!

**Comment by watrall** [comment] 2019-04-19 19:50
where are the map tiles for the geolocation map being pulled from?

**Comment by Dev34** [comment] 2019-04-19 22:47
@watrall We're using [Leaflet](https://leafletjs.com/), which is an open-source Javascript library. The actual map data that Leaflet uses is pulled from [OpenStreetMap](https://www.openstreetmap.org/about).

**Closed** 2019-05-30 15:12 UTC
Labels: Enhancement, Front-end, Wanted
