### ISSUE TITLE
Pagination broken 

### ISSUE THREAD

**Issue by asheill** [matrix-msu/Kora3#190] opened 2018-06-28 18:58 UTC
e.k3/projects/11/forms/9/records

Pagination is broken. Selecting "Next Page" button or the next page # directs me back to the main project list.

**Comment by fritosxii** [comment] 2018-06-28 19:00
Duplicate of #166

**Comment by fritosxii** [comment] 2018-06-28 19:50
This won't actually be fixed by #166. There is an https issue

**Comment by fritosxii** [comment] 2018-06-29 12:49
Laravel url function and pagination url functions now force https in production

**Closed by fritosxii** 2018-06-29 12:49 UTC
Labels: Back-end, Bug, Critical
