### ISSUE TITLE
Replay Kora Intro Onboarding

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#387] opened 2018-11-20 19:41 UTC
On the my preferences page, I commented out a section for replaying the Introduction Onboarding. This section should be refined and added back in AFTER the Kora intro onboarding is a thing.

**Comment by suuuth** [comment] 2019-01-24 19:40
duplicate of #336 .  Closing this issue

**Closed** 2019-01-25 14:31 UTC
Labels: Enhancement, Front-end, Wanted
