### ISSUE TITLE
Project Card - On Main Projects Page - If the project doesn't have any forms...

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#21] opened 2018-03-05 18:55 UTC
... the project forms listing on the project card should say "No forms" instead of just being blank.

**Comment by suuuth** [comment] 2018-05-29 19:51
http://dev2.matrix.msu.edu/~kevin.sutherland/Kora3/public/projects/197

**Comment by suuuth** [comment] 2018-05-29 19:57
duplicate of #58

**Comment by fritosxii** [comment] 2018-06-18 19:18
Closing because of duplication

**Closed by fritosxii** 2018-06-18 19:18 UTC
